# Note that external tests will run on manual triggers.

trigger:
  branches:
    include:
    - main
  tags:
    include:
    - release-*

# Trigger a build when there is a pull request to the main branch
# Ignore PRs that are just updating the docs, but still run when
# a notebook under doc/ changes since those are executed as tests.
pr:
  autoCancel: true
  branches:
    include:
    - main
  paths:
    exclude:
    - doc
    - README.rst
    include:
    - doc/*.ipynb
    - "*"

schedules:
- cron: "0 3 * * *"  # 10pm EST/11pm EDT
  displayName: NightlyTests
  branches:
    include:
    - main
  always: true
- cron: "0 4 * * 6"  # 11pm EST/12am EDT
  displayName: WeeklyTests
  branches:
    include:
    - main
  always: true

parameters:
  - name: includeReleaseCandidates
    displayName: "Allow pre-release dependencies"
    type: boolean
    default: false

variables:
  triggeredByPullRequest: $[eq(variables['Build.Reason'], 'PullRequest')]

stages:
  - stage: RunAllTests
    displayName: Run test suite
    jobs:
    - job: CheckBlackFormatting
      displayName: 'Check code formatting with black'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.10'
        displayName: 'Use Python 3.10'
      
      - script: |
          python -m pip install --upgrade pip
          python -m pip install -U uv
          uv sync --extra dev --python 3.10
        displayName: 'Install dependencies'
      
      - script: |
          uv run black --check --diff --target-version py310 toponymy/ doc/
        displayName: 'Check black formatting'

    - job: DetectChangedNotebooks
      condition: and(eq(variables['Build.Reason'], 'PullRequest'), not(canceled()))
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - checkout: none
        - bash: |
            set -e
            if [ "$(Build.Reason)" != "PullRequest" ]; then
              echo "##vso[task.setvariable variable=CHANGED_NOTEBOOKS;isOutput=true]"
              exit 0
            fi

            PR_NUMBER=$(System.PullRequest.PullRequestNumber)
            echo "PR_NUMBER=$PR_NUMBER"

            RESPONSE=$(curl -s \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/TutteInstitute/toponymy/pulls/$PR_NUMBER/files?per_page=100")

            CHANGED=$(echo "$RESPONSE" \
            | jq -r '.[].filename' \
            | grep '\.ipynb$' \
            | xargs -n1 basename \
            | paste -sd, -)

            echo "Changed notebooks: $CHANGED"
            echo "##vso[task.setvariable variable=CHANGED_NOTEBOOKS;isOutput=true]$CHANGED"
          displayName: 'Detect changed notebooks in PR'
          name: detect

    - job: PRTests
      timeoutInMinutes: 150   # default is usually 60
      dependsOn: DetectChangedNotebooks
      pool:
        vmImage: $(imageName)
      workspace:
        clean: all
      variables:
        CHANGED_NOTEBOOKS: $[ dependencies.DetectChangedNotebooks.outputs['detect.CHANGED_NOTEBOOKS'] ]
      strategy:
        matrix:
          linux_py310:
            imageName: 'ubuntu-latest'
            python.version: '3.10'
          # windows_py310:
          #   imageName: 'windows-latest'
          #   python.version: '3.10'
          # mac_py311:
          #   imageName: 'macOS-latest'
          #   python.version: '3.11'
          linux_py311:
            imageName: 'ubuntu-latest'
            python.version: '3.11'
          # windows_py311:
          #   imageName: 'windows-latest'
          #   python.version: '3.11'
          # mac_py312:
          #   imageName: 'macOS-latest'
          #   python.version: '3.12'
          linux_py312:
            imageName: 'ubuntu-latest'
            python.version: '3.12'
          # windows_py312:
          #   imageName: 'windows-latest'
          #   python.version: '3.12'
          # linux_py313:
          #   imageName: 'ubuntu-latest'
          #   python.version: '3.13'
          # windows_py313:
          #   imageName: 'windows-latest'
          #   python.version: '3.13'
          # mac_py313:
          #   imageName: 'macOS-latest'
          #   python.version: '3.13'
      condition: and(or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Manual')), not(canceled()))
      steps:
      - template: .azure/templates/pr-test-job.yml
        parameters:
          installOllama: true
          includeReleaseCandidates: ${{ parameters.includeReleaseCandidates }}

    - job: NotebookTests
      timeoutInMinutes: 150   # default is usually 60
      pool:
        vmImage: 'ubuntu-latest'
      workspace:
        clean: all
      strategy:
        matrix:
          linux_py310:
            imageName: 'ubuntu-latest'
            python.version: '3.10'
          linux_py313:
            imageName: 'ubuntu-latest'
            python.version: '3.13'
      condition: or(and(eq(variables['Build.Reason'], 'Schedule'), eq(variables['Build.CronSchedule.DisplayName'], 'WeeklyTests')), eq(variables['Build.Reason'], 'Manual'))
      steps:
      - template: .azure/templates/notebook-test-job.yml
        parameters:
          installOllama: true
          includeReleaseCandidates: ${{ parameters.includeReleaseCandidates }}

    - job: ExternalTests
      timeoutInMinutes: 30
      pool:
        vmImage: 'ubuntu-latest'
      workspace:
        clean: all
      strategy:
        matrix:
          linux_py311:
            imageName: 'ubuntu-latest'
            python.version: '3.11'
      condition: and(or(and(eq(variables['Build.Reason'], 'Schedule'), eq(variables['Build.CronSchedule.DisplayName'], 'NightlyTests')), eq(variables['Build.Reason'], 'Manual')), not(canceled()))
      steps:
      - template: .azure/templates/external-test-job.yml
        parameters:
          includeReleaseCandidates: ${{ parameters.includeReleaseCandidates }}
          showCapture: 'stdout'

  - stage: BuildPublishArtifact
    dependsOn: RunAllTests
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/release-'), eq(variables.triggeredByPullRequest, false), not(canceled()))
    jobs:
      - job: BuildArtifacts
        timeoutInMinutes: 90
        displayName: Build source dists and wheels
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.10'
          displayName: 'Use Python 3.10'

        - script: |
            python -m pip install --upgrade pip
            python -m pip install -U uv
            uv sync --extra llama --python "$(python -c 'import sys; print(sys.executable)')"
          displayName: 'Install dependencies'

        - script: |
            uv build --no-sources --sdist --wheel
          displayName: 'Build package'

        - bash: |
            export PACKAGE_VERSION="$(uv version --short)"
            echo "Package Version: ${PACKAGE_VERSION}"
            echo "##vso[task.setvariable variable=packageVersionFormatted;]release-${PACKAGE_VERSION}"
          displayName: 'Get package version'

        - script: |
            echo "Version in git tag $(Build.SourceBranchName) does not match version derived from setup.py $(packageVersionFormatted)"
            exit 1
          displayName: Raise error if version doesnt match tag
          condition: and(succeeded(), ne(variables['Build.SourceBranchName'], variables['packageVersionFormatted']))

        - task: DownloadSecureFile@1
          name: PYPIRC_CONFIG
          displayName: 'Download pypirc'
          inputs:
            secureFile: 'pypirc'

        - script: |
            uvx twine check dist/*
            uvx twine upload --repository pypi --config-file $(PYPIRC_CONFIG.secureFilePath) dist/*
          displayName: 'Upload to PyPI'
          condition: and(succeeded(), eq(variables['Build.SourceBranchName'], variables['packageVersionFormatted']))
