# Trigger a build when there is a push to the main branch or a tag starts with release-
trigger:
  branches:
    include:
    - main
  tags:
    include:
    - release-*

# Trigger a build when there is a pull request to the main branch
# Ignore PRs that are just updating the docs
pr:
  branches:
    include:
    - main
    exclude:
    - doc/*
    - README.rst

parameters:
  - name: includeReleaseCandidates
    displayName: "Allow pre-release dependencies"
    type: boolean
    default: false

variables:
  triggeredByPullRequest: $[eq(variables['Build.Reason'], 'PullRequest')]

stages:
  - stage: RunAllTests
    displayName: Run test suite
    jobs:
      - job: run_platform_tests
        strategy:
          matrix:
            mac_py310:
              imageName: 'macOS-latest'
              python.version: '3.10'
            linux_py310:
              imageName: 'ubuntu-latest'
              python.version: '3.10'
            windows_py310:
              imageName: 'windows-latest'
              python.version: '3.10'
            mac_py311:
              imageName: 'macOS-latest'
              python.version: '3.11'
            linux_py311:
              imageName: 'ubuntu-latest'
              python.version: '3.11'
            windows_py311:
              imageName: 'windows-latest'
              python.version: '3.11'
            mac_py312:
              imageName: 'macOS-latest'
              python.version: '3.12'
            linux_py312:
              imageName: 'ubuntu-latest'
              python.version: '3.12'
            windows_py312:
              imageName: 'windows-latest'
              python.version: '3.12'
        pool:
          vmImage: $(imageName)

        steps:
        # Use conda instead of UsePythonVersion
        - task: CondaEnvironment@1
          inputs:
            createCustomEnvironment: true
            environmentName: 'test-env'
            packageSpecs: 'python=$(python.version)'
            updateConda: true
          displayName: 'Create Conda Environment'

        # Install core scientific packages via conda-forge
        - script: |
            conda install -y -c conda-forge \
              pytorch>=2.3 \
              numpy>=2.0 \
              pandas>=1.0 \
              scipy \
              scikit-learn>=1.6 \
              numba>=0.56
          displayName: 'Install conda packages'

        # Install additional packages that work better from conda on macOS
        - script: |
            conda install -y -c conda-forge \
              transformers>=4.35 \
              sentence-transformers>=2.2 \
              tokenizers
          displayName: 'Install NLP packages via conda'
          condition: eq(variables['Agent.OS'], 'Darwin')

        # Install remaining packages via pip
        - script: |
            python -m pip install --upgrade pip
            pip install datasets vectorizers fast_hdbscan>=0.2.2 
            pip install dataclasses tqdm tenacity aiohttp
          displayName: 'Install pip packages'

        # For non-macOS, install transformers via pip if not already installed
        - script: |
            pip install transformers>=4.35 sentence-transformers>=2.2
          displayName: 'Install NLP packages via pip'
          condition: ne(variables['Agent.OS'], 'Darwin')

        # Install test requirements
        - script: |
            pip install black isort pylint pytest umap-learn
            pip install anthropic cohere openai azure-ai-inference 
            pip install llama-cpp-python mistralai pytest-asyncio bm25s evoc
          displayName: 'Install test dependencies'

        - script: |
            pip install -e .
            pip install pytest-azurepipelines pytest-cov coveralls
          displayName: 'Install package'

        # Verify installations
        - script: |
            python -c "import torch; print(f'PyTorch: {torch.__version__}')"
            python -c "import numpy; print(f'NumPy: {numpy.__version__}')"
            python -c "import transformers; print(f'Transformers: {transformers.__version__}')"
            python -c "import sentence_transformers; print(f'Sentence Transformers: {sentence_transformers.__version__}')"
          displayName: 'Verify package versions'

        - script: |
            pytest toponymy/tests --show-capture=no -v --disable-warnings --junitxml=junit/test-results.xml --cov=toponymy/ --cov-report=xml --cov-report=html
          displayName: 'Run tests'

        - bash: |
            coveralls
          displayName: 'Publish to coveralls'
          condition: and(succeeded(), eq(variables.triggeredByPullRequest, false))
          env:
            COVERALLS_REPO_TOKEN: $(COVERALLS_TOKEN)

        - task: PublishTestResults@2
          inputs:
            testResultsFiles: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
            testRunTitle: '$(Agent.OS) - $(Build.BuildNumber)[$(Agent.JobName)] - Python $(python.version)'
          condition: succeededOrFailed()

  - stage: BuildPublishArtifact
    dependsOn: RunAllTests
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/release-'), eq(variables.triggeredByPullRequest, false))
    jobs:
      - job: BuildArtifacts
        displayName: Build source dists and wheels    
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.10'
          displayName: 'Use Python 3.10'

        - script: |
            python -m pip install --upgrade pip
            pip install wheel
            pip install -r requirements.txt
          displayName: 'Install dependencies'

        - script: |
            pip install -e .
          displayName: 'Install package locally'
        
        - script: |
            python setup.py sdist bdist_wheel
          displayName: 'Build package'

        - bash: |
            export PACKAGE_VERSION="$(python setup.py --version)"
            echo "Package Version: ${PACKAGE_VERSION}"
            echo "##vso[task.setvariable variable=packageVersionFormatted;]release-${PACKAGE_VERSION}"
          displayName: 'Get package version'

        - script: |
            echo "Version in git tag $(Build.SourceBranchName) does not match version derived from setup.py $(packageVersionFormatted)"
            exit 1
          displayName: Raise error if version doesnt match tag
          condition: and(succeeded(), ne(variables['Build.SourceBranchName'], variables['packageVersionFormatted']))

        - task: DownloadSecureFile@1
          name: PYPIRC_CONFIG
          displayName: 'Download pypirc'
          inputs:
            secureFile: 'pypirc'  

        - script: |
            pip install twine
            twine upload --repository pypi --config-file $(PYPIRC_CONFIG.secureFilePath) dist/* 
          displayName: 'Upload to PyPI'
          condition: and(succeeded(), eq(variables['Build.SourceBranchName'], variables['packageVersionFormatted']))